---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.1.1
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "debian-10"
          - "centos-6"
          - "centos-7"
          - "centos-8"
          - "centos-stream-8"
          - "fedora-latest"
          - "ubuntu-1804"
          - "ubuntu-2004"
        suite:
          - "default"
          - "delete"
        exclude:
          # These work locally but fail on GH actions for reasons unknown to man
          - os: "ubuntu-1804"
            suite: "delete"
          - os: "ubuntu-2004"
            suite: "delete"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Dokken
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
